const express = require("express");
const router = express.Router();
const fs = require("fs");
const PDFDocument = require("pdfkit");
const pool = require("./db");
const sendGoogleEmail = require("./sendGoogleEmail");

// FETCH TODO FROM DB (Used in both download + email modes)
async function getTodoData(todo_id) {
    const todo = await pool.query(
        `SELECT 
            t.*, 
            u1.username AS created_by, 
            u2.username AS updated_by
        FROM todo t
        LEFT JOIN users u1 ON t.created_by = u1.user_id
        LEFT JOIN users u2 ON t.updated_by = u2.user_id
        WHERE t.todo_id = $1`,
        [todo_id]
    );

    if (todo.rows.length === 0) return null;

    return todo.rows[0];
}

// BUILD PDF (returns PATH of saved PDF)
async function buildPDF(todo, todo_id) {
    return new Promise((resolve, reject) => {
        const path = `${__dirname}/PDFs/todo_${todo_id}.pdf`;
        const doc = new PDFDocument({ margin: 50 });

        const stream = fs.createWriteStream(path);
        doc.pipe(stream);

        /* HEADER */
        doc.rect(50, 40, 500, 40)
            .fill("#007bff")
            .stroke()
            .fillColor("white")
            .fontSize(22)
            .text("TODO DETAILS", 50, 50, {
                width: 500,
                align: "center"
            })
            .fillColor("black");

        doc.moveDown(3);

        /* TABLE LAYOUT */
        const labelX = 60;
        const valueX = 250;
        let startY = 120;
        const lineHeight = 28;

        const safe = (v) => (v !== null && v !== undefined ? String(v) : "-");

        function printRow(label, value) {
            doc.font("Helvetica-Bold")
                .fontSize(13)
                .text(label, labelX, startY);

            doc.font("Helvetica")
                .fontSize(13)
                .text(safe(value), valueX, startY);

            startY += lineHeight;

            doc.moveTo(50, startY - 8)
                .lineTo(550, startY - 8)
                .strokeColor("#e0e0e0")
                .stroke()
                .strokeColor("black");
        }

        // Rows
        printRow("Description", todo.description);
        printRow("Amount", todo.amount);
        printRow("Created By", todo.created_by);
        printRow("Updated By", todo.updated_by);
        printRow("Created At", new Date(todo.created_at).toLocaleString());
        printRow("Updated At", new Date(todo.updated_at).toLocaleString());

        /* FOOTER */

        const pageWidth = doc.page.width;
        const margin = 50;
        const footerWidth = pageWidth - margin * 2;

        doc.moveDown(3);

        doc.fontSize(10)
            .fillColor("gray")
            .text("PDF generated by Stylic Todo App", margin, startY + 20, {
                width: footerWidth,
                align: "center"
            });

        doc.fontSize(10)
            .fillColor("gray")
            .text(`Generated on: ${new Date().toLocaleString()}`, margin, startY + 35, {
                width: footerWidth,
                align: "center"
            });

        /* END PDF */
        doc.end();

        stream.on("finish", () => resolve(path));
        stream.on("error", err => reject(err));
    });
}

// UNIVERSAL ROUTE (download OR email)
router.post("/", async (req, res) => {
    try {
        const { todo_id, mode, to, subject, message } = req.body;

        if (!todo_id || !mode)
            return res.status(400).json({ error: "todo_id and mode are required" });

        const todo = await getTodoData(todo_id);
        if (!todo)
            return res.status(404).json({ error: "Todo not found" });

        // Generate PDF file
        const pdfPath = await buildPDF(todo, todo_id);

        // MODE: DOWNLOAD
        if (mode === "download") {
            res.setHeader("Content-Type", "application/pdf");
            res.setHeader("Content-Disposition", `attachment; filename=todo_${todo_id}.pdf`);
            const fileStream = fs.createReadStream(pdfPath);
            return fileStream.pipe(res);
        }

        // MODE: EMAIL
        if (mode === "email") {
            if (!to || !subject || !message)
                return res.status(400).json({ error: "Email fields missing" });

            const pdfData = fs.readFileSync(pdfPath);
            const pdfBase64 = pdfData.toString("base64");

            const emailBody =
                `From: "Soham" <${process.env.GC_SENDER_EMAIL}>
To: ${to}
Subject: ${subject}
Content-Type: multipart/mixed; boundary="boundary123"

--boundary123
Content-Type: text/plain; charset="UTF-8"

${message}

--boundary123
Content-Type: application/pdf
Content-Disposition: attachment; filename="todo_${todo_id}.pdf"
Content-Transfer-Encoding: base64

${pdfBase64}

--boundary123--
`;

            await sendGoogleEmail(emailBody);
            return res.json({ success: true, message: "Email sent with PDF!" });
        }

        return res.status(400).json({ error: "Invalid mode" });

    } catch (err) {
        console.error("TODO ACTION ERROR →", err);
        res.status(500).json({ error: "Internal Server Error" });
    }
});

module.exports = router;